# Site settings
title: Cultivating Awesome
email: christi@limerentfox.com
description: > # this means to ignore newlines until "baseurl:"
  Musings From a Caffeine Addicted Curator
baseurl:  /cultivating-awesome/
url:  # the base hostname & protocol for your site
twitter_username: limerentfox
github_username:  limerentfox

# Build settings
markdown: kramdown

# highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"
